#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("SellNow.Resource", IsApplication=true)]

namespace SellNow
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int action_menu = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int categorias = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int cerca = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int imagenPerfil = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int inicio = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int lamparas = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int perfil = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050030
			public const int GridLayout1 = 2131034160;
			
			// aapt resource value: 0x7f050005
			public const int MenuButton = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int MenuButtonProducto = 2131034122;
			
			// aapt resource value: 0x7f050017
			public const int SellNowContainer = 2131034135;
			
			// aapt resource value: 0x7f050000
			public const int SellNowContent = 2131034112;
			
			// aapt resource value: 0x7f050018
			public const int SellNowMenu = 2131034136;
			
			// aapt resource value: 0x7f050023
			public const int categoriasMenuName = 2131034147;
			
			// aapt resource value: 0x7f050026
			public const int cercaMenuName = 2131034150;
			
			// aapt resource value: 0x7f05000c
			public const int columna1 = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int columna2 = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int columna3 = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int correoInfoUser = 2131034127;
			
			// aapt resource value: 0x7f05002b
			public const int descripcion = 2131034155;
			
			// aapt resource value: 0x7f050009
			public const int description1 = 2131034121;
			
			// aapt resource value: 0x7f050028
			public const int email = 2131034152;
			
			// aapt resource value: 0x7f050016
			public const int faceebokLoginButton = 2131034134;
			
			// aapt resource value: 0x7f050011
			public const int fechaRegistroInfoUser = 2131034129;
			
			// aapt resource value: 0x7f050001
			public const int frameLayout1 = 2131034113;
			
			// aapt resource value: 0x7f050021
			public const int goCategorias = 2131034145;
			
			// aapt resource value: 0x7f050024
			public const int goCerca = 2131034148;
			
			// aapt resource value: 0x7f05001a
			public const int goHome = 2131034138;
			
			// aapt resource value: 0x7f05001d
			public const int goPerfil = 2131034141;
			
			// aapt resource value: 0x7f050015
			public const int googleLoginButton = 2131034133;
			
			// aapt resource value: 0x7f050022
			public const int iconCategorias = 2131034146;
			
			// aapt resource value: 0x7f050025
			public const int iconCerca = 2131034149;
			
			// aapt resource value: 0x7f05001b
			public const int iconInicio = 2131034139;
			
			// aapt resource value: 0x7f05001e
			public const int iconPerfil = 2131034142;
			
			// aapt resource value: 0x7f050008
			public const int image1 = 2131034120;
			
			// aapt resource value: 0x7f05000b
			public const int infoUsuario = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int item1 = 2131034119;
			
			// aapt resource value: 0x7f050031
			public const int lblVulling = 2131034161;
			
			// aapt resource value: 0x7f050004
			public const int linearLayout1 = 2131034116;
			
			// aapt resource value: 0x7f050012
			public const int login = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int loginButton = 2131034131;
			
			// aapt resource value: 0x7f05002a
			public const int modificarDatosButton = 2131034154;
			
			// aapt resource value: 0x7f050027
			public const int nombre = 2131034151;
			
			// aapt resource value: 0x7f05000d
			public const int nombreInfoUser = 2131034125;
			
			// aapt resource value: 0x7f05002d
			public const int nuevaSubastaButton = 2131034157;
			
			// aapt resource value: 0x7f050034
			public const int pass1 = 2131034164;
			
			// aapt resource value: 0x7f050035
			public const int pass2 = 2131034165;
			
			// aapt resource value: 0x7f050029
			public const int password = 2131034153;
			
			// aapt resource value: 0x7f05001f
			public const int perfilMenuName = 2131034143;
			
			// aapt resource value: 0x7f05002c
			public const int precioInicial = 2131034156;
			
			// aapt resource value: 0x7f050033
			public const int pujar = 2131034163;
			
			// aapt resource value: 0x7f050014
			public const int registerButton = 2131034132;
			
			// aapt resource value: 0x7f050006
			public const int searchView1 = 2131034118;
			
			// aapt resource value: 0x7f050032
			public const int seekBar1 = 2131034162;
			
			// aapt resource value: 0x7f050019
			public const int sellNowMenuHeader = 2131034137;
			
			// aapt resource value: 0x7f05001c
			public const int sellNowMenuName = 2131034140;
			
			// aapt resource value: 0x7f05002e
			public const int textView1 = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int textView2 = 2131034159;
			
			// aapt resource value: 0x7f050002
			public const int view1 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int view2 = 2131034115;
			
			// aapt resource value: 0x7f050020
			public const int view3 = 2131034144;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ContentLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DatosUsuario = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MenuLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int modificarDatosUsuario = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int NuevaSubasta = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Producto = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Registro = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
